version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  servicetaxes:
    container_name: servicetaxes
    image: servicetaxes:latest
    depends_on:
      - "salaryservice"
    build:
      context: servicetaxes
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - services-network
  
  salaryservice:
    container_name: salaryservice
    image: salaryservice:latest
    build:
      context: salaryservice
      dockerfile: Dockerfile    
    networks:
      - services-network
